//! The type-level mapping DSL: the `M` / `AxisName` traits and the expression
//! primitives the `m!` / `axes!` macros expand into.

use std::fmt::Debug;
use std::marker::PhantomData;

use abi_stable::std_types::RBox;
use furiosa_opt_macro::primitive;

use crate::{Atom, Ident, Index, Mapping, PaddingKind, Term};

/// Marker trait for axis names. Implemented by types generated by `axes!`.
pub trait AxisName: Debug + Clone + 'static {
    /// The identifier of this axis (e.g. `Ident::K`).
    const NAME: Ident;
    /// The size of this axis as declared in `axes!`.
    const SIZE: usize;
}

/// Mapping expression that describes memory layout and computes size for a given shape.
#[primitive(mapping::M)]
// ANCHOR: trait_m
pub trait M: Debug + Clone {
    /// The computed size for the given shape.
    const SIZE: usize;

    /// Converts the mapping expression type into a value.
    fn to_value() -> Mapping;

    /// Converts a buffer index to a tensor index, returning `None` if out-of-bounds.
    fn map(i: usize) -> Option<Index>;
}
// ANCHOR_END: trait_m

/// Broadcast expression: `SIZE` iterations of a stride-0 (don't-care) axis.
/// `Broadcast<1>` is the identity (the unit written `m![1]`).
/// `SIZE > 1` lowers in shape conversion to a non-target `Tile` fill.
#[primitive(mapping::Broadcast)]
#[derive(Debug, Clone)]
pub struct Broadcast<const SIZE: usize>;

// ANCHOR: broadcast_impl
impl<const SIZE: usize> M for Broadcast<SIZE> {
    const SIZE: usize = SIZE;

    fn to_value() -> Mapping {
        Mapping::Broadcast { size: SIZE }
    }

    fn map(i: usize) -> Option<Index> {
        // Every iteration shares one logical value (the pointer never moves),
        // so the tensor index carries no terms.
        (i < SIZE).then(Index::new)
    }
}
// ANCHOR_END: broadcast_impl

// ANCHOR: identity_impl
/// The identity mapping (size-1 broadcast), the unit written `m![1]`.
pub type Identity = Broadcast<1>;
// ANCHOR_END: identity_impl

/// Symbol expression that represents a single axis.
#[primitive(mapping::Symbol)]
#[derive(Debug, Clone)]
pub struct Symbol<S: AxisName> {
    _marker: PhantomData<S>,
}

// ANCHOR: symbol_impl
impl<S: AxisName> M for Symbol<S> {
    const SIZE: usize = S::SIZE;

    fn to_value() -> Mapping {
        Mapping::Symbol {
            symbol: S::NAME,
            size: S::SIZE,
        }
    }

    fn map(i: usize) -> Option<Index> {
        (i < S::SIZE).then(|| {
            let mut index = Index::new();
            index.add_term(
                Term {
                    inner: Atom::Symbol {
                        symbol: S::NAME,
                        size: S::SIZE,
                    },
                    stride: 1,
                    modulo: S::SIZE,
                },
                i,
            );
            index
        })
    }
}
// ANCHOR_END: symbol_impl

/// Stride expression that represents one for every `SIZE` elements.
#[primitive(mapping::Stride)]
#[derive(Debug, Clone)]
pub struct Stride<L, const SIZE: usize> {
    _marker: PhantomData<L>,
}
// ANCHOR: stride_impl
impl<L, const SIZE: usize> M for Stride<L, SIZE>
where
    L: M,
{
    const SIZE: usize = {
        assert!(L::SIZE % SIZE == 0, "Stride size must divide the original size");
        L::SIZE / SIZE
    };

    fn to_value() -> Mapping {
        Mapping::Stride {
            inner: RBox::new(L::to_value()),
            stride: SIZE,
        }
    }

    fn map(i: usize) -> Option<Index> {
        if i < Self::SIZE { L::map(i * SIZE) } else { None }
    }
}
// ANCHOR_END: stride_impl

/// Modulo expression that represents modulo `SIZE` elements.
#[primitive(mapping::Modulo)]
#[derive(Debug, Clone)]
pub struct Modulo<L, const SIZE: usize> {
    _marker: PhantomData<L>,
}
// ANCHOR: modulo_impl
impl<L, const SIZE: usize> M for Modulo<L, SIZE>
where
    L: M,
{
    const SIZE: usize = {
        assert!(L::SIZE % SIZE == 0, "Modulo size must divide the original size");
        SIZE
    };

    fn to_value() -> Mapping {
        Mapping::Modulo {
            inner: RBox::new(L::to_value()),
            modulo: SIZE,
        }
    }

    fn map(i: usize) -> Option<Index> {
        if i < Self::SIZE { L::map(i % L::SIZE) } else { None }
    }
}
// ANCHOR_END: modulo_impl

/// Truncate expression to `SIZE` elements.
#[primitive(mapping::Resize)]
#[derive(Debug, Clone)]
pub struct Resize<L, const SIZE: usize> {
    _marker: PhantomData<L>,
}
// ANCHOR: resize_impl
impl<L, const SIZE: usize> M for Resize<L, SIZE>
where
    L: M,
{
    const SIZE: usize = SIZE;

    fn to_value() -> Mapping {
        Mapping::Resize {
            inner: RBox::new(L::to_value()),
            resize: SIZE,
        }
    }

    fn map(i: usize) -> Option<Index> {
        if i < SIZE { L::map(i) } else { None }
    }
}
// ANCHOR_END: resize_impl

/// Add padding to increase an expression's size.
///
/// `KIND` selects the padding flavour at the type level. Defaults to
/// [`PaddingKind::Top`] (arbitrary values); use [`PaddingKind::Zero`] for
/// slots known to hold zero (e.g. produced by the Fetch Adapter's masking
/// stage), or [`PaddingKind::Bottom`] for inaccessible regions.
#[primitive(mapping::Padding)]
#[derive(Debug, Clone)]
pub struct Padding<L, const SIZE: usize, const KIND: PaddingKind = { PaddingKind::Top }> {
    _marker: PhantomData<L>,
}
// ANCHOR: padding_impl
impl<L, const SIZE: usize, const KIND: PaddingKind> M for Padding<L, SIZE, KIND>
where
    L: M,
{
    const SIZE: usize = SIZE;

    fn to_value() -> Mapping {
        Mapping::Padding {
            inner: RBox::new(L::to_value()),
            padding: SIZE,
            kind: KIND,
        }
    }

    fn map(i: usize) -> Option<Index> {
        L::map(i)
    }
}
// ANCHOR_END: padding_impl

/// Pair expression of two expressions.
#[primitive(mapping::Pair)]
#[derive(Debug, Clone)]
pub struct Pair<L, R> {
    _marker: PhantomData<(L, R)>,
}
// ANCHOR: pair_impl
impl<L, R> M for Pair<L, R>
where
    L: M,
    R: M,
{
    const SIZE: usize = L::SIZE * R::SIZE;

    fn to_value() -> Mapping {
        Mapping::Pair {
            left: RBox::new(L::to_value()),
            right: RBox::new(R::to_value()),
        }
    }

    fn map(i: usize) -> Option<Index> {
        let mut l = L::map(i / R::SIZE)?;
        let r = R::map(i % R::SIZE)?;
        l.add(r);
        Some(l)
    }
}
// ANCHOR_END: pair_impl
