//! The type-level mapping DSL: the `M` / `AxisName` traits and the expression
//! primitives the `m!` / `axes!` macros expand into.

use std::fmt::Debug;
use std::marker::PhantomData;

use abi_stable::std_types::RBox;
use furiosa_opt_macro::primitive;

use crate::{Atom, Cell, Ident, Index, Mapping, PaddingKind, Term};

/// Marker trait for axis names. Implemented by types generated by `axes!`.
pub trait AxisName: Debug + Clone + 'static {
    /// The identifier of this axis (e.g. `Ident::K`).
    const NAME: Ident;
    /// The size of this axis as declared in `axes!`.
    const SIZE: usize;
}

/// Mapping expression that describes memory layout and computes size for a given shape.
#[primitive(mapping::M)]
// ANCHOR: trait_m
pub trait M: Debug + Clone {
    /// The computed size for the given shape.
    const SIZE: usize;

    /// Converts the mapping expression type into a value.
    fn to_value() -> Mapping;

    /// Converts a buffer index to a physical cell result.
    fn map(i: usize) -> Cell;
}
// ANCHOR_END: trait_m

/// A mapping whose size is a count, which is what an operator takes as its factor.
///
/// [`Broadcast`] counts a literal, [`Symbol`] counts an axis, and [`Stride`] counts how many of
/// something fits: `m![Width / 512]` is however many 512-wide pieces `Width` holds. Every other
/// mapping has a size without counting anything, so none is a factor: [`Pair`] multiplies two
/// shapes together, and the remaining operators only repeat the factor they were given.
///
/// ```compile_fail,E0277
/// use furiosa_mapping_types::*;
/// struct A;
/// impl AxisName for A {
///     const NAME: Ident = Ident::A;
///     const SIZE: usize = 8;
/// }
/// // A pair is a shape, not a count, so it cannot be a stride.
/// let _ = <Stride<Symbol<A>, Pair<Symbol<A>, Symbol<A>>> as M>::SIZE;
/// ```
pub trait Count: M {}

/// Broadcast expression: `SIZE` iterations of a stride-0 (don't-care) axis.
/// `Broadcast<1>` is the identity (the unit written `m![1]`).
/// `SIZE > 1` lowers in shape conversion to a non-target `Tile` fill.
#[primitive(mapping::Broadcast)]
#[derive(Debug, Clone)]
pub struct Broadcast<const SIZE: usize>;

// ANCHOR: broadcast_impl
impl<const SIZE: usize> M for Broadcast<SIZE> {
    const SIZE: usize = SIZE;

    fn to_value() -> Mapping {
        Mapping::Broadcast { size: SIZE }
    }

    fn map(i: usize) -> Cell {
        if i < SIZE {
            Cell::Index(Index::new())
        } else {
            Cell::OutOfBounds
        }
    }
}
// ANCHOR_END: broadcast_impl

impl<const SIZE: usize> Count for Broadcast<SIZE> {}

// ANCHOR: identity_impl
/// The identity mapping (size-1 broadcast), the unit written `m![1]`.
pub type Identity = Broadcast<1>;
// ANCHOR_END: identity_impl

/// Symbol expression that represents a single axis.
#[primitive(mapping::Symbol)]
#[derive(Debug, Clone)]
pub struct Symbol<S: AxisName> {
    _marker: PhantomData<S>,
}

// ANCHOR: symbol_impl
impl<S: AxisName> M for Symbol<S> {
    const SIZE: usize = S::SIZE;

    fn to_value() -> Mapping {
        Mapping::Symbol {
            symbol: S::NAME,
            size: S::SIZE,
        }
    }

    fn map(i: usize) -> Cell {
        if i >= S::SIZE {
            return Cell::OutOfBounds;
        }
        Cell::Index({
            let mut index = Index::new();
            index.add_term(
                Term {
                    inner: Atom::Symbol {
                        symbol: S::NAME,
                        size: S::SIZE,
                    },
                    stride: 1,
                    modulo: S::SIZE,
                },
                i,
            );
            index
        })
    }
}
// ANCHOR_END: symbol_impl

impl<S: AxisName> Count for Symbol<S> {}

/// Stride expression that represents one for every element the factor mapping names.
///
/// `F` carries the stride in type space. Literal factors use [`Broadcast`]; an axis factor uses
/// [`Symbol`], avoiding a size read from a generic parameter in const-argument position.
#[primitive(mapping::Stride)]
#[derive(Debug, Clone)]
pub struct Stride<L, F> {
    _marker: PhantomData<(L, F)>,
}
// ANCHOR: stride_impl
impl<L, F> M for Stride<L, F>
where
    L: M,
    F: Count,
{
    const SIZE: usize = {
        assert!(L::SIZE % F::SIZE == 0, "Stride size must divide the original size");
        L::SIZE / F::SIZE
    };

    fn to_value() -> Mapping {
        Mapping::Stride {
            inner: RBox::new(L::to_value()),
            stride: F::SIZE,
        }
    }

    fn map(i: usize) -> Cell {
        if i < Self::SIZE {
            L::map(i * F::SIZE)
        } else {
            Cell::OutOfBounds
        }
    }
}
// ANCHOR_END: stride_impl

impl<L: M, F: Count> Count for Stride<L, F> {}

/// Modulo expression that represents the factor mapping's extent.
#[primitive(mapping::Modulo)]
#[derive(Debug, Clone)]
pub struct Modulo<L, F> {
    _marker: PhantomData<(L, F)>,
}
// ANCHOR: modulo_impl
impl<L, F> M for Modulo<L, F>
where
    L: M,
    F: Count,
{
    const SIZE: usize = {
        assert!(L::SIZE % F::SIZE == 0, "Modulo size must divide the original size");
        F::SIZE
    };

    fn to_value() -> Mapping {
        Mapping::Modulo {
            inner: RBox::new(L::to_value()),
            modulo: F::SIZE,
        }
    }

    fn map(i: usize) -> Cell {
        if i < Self::SIZE {
            L::map(i % L::SIZE)
        } else {
            Cell::OutOfBounds
        }
    }
}
// ANCHOR_END: modulo_impl

/// Truncate expression to the factor mapping's extent.
#[primitive(mapping::Resize)]
#[derive(Debug, Clone)]
pub struct Resize<L, F> {
    _marker: PhantomData<(L, F)>,
}
// ANCHOR: resize_impl
impl<L, F> M for Resize<L, F>
where
    L: M,
    F: Count,
{
    const SIZE: usize = F::SIZE;

    fn to_value() -> Mapping {
        Mapping::Resize {
            inner: RBox::new(L::to_value()),
            resize: F::SIZE,
        }
    }

    fn map(i: usize) -> Cell {
        if i < F::SIZE { L::map(i) } else { Cell::OutOfBounds }
    }
}
// ANCHOR_END: resize_impl

/// Add padding to increase an expression's size.
///
/// `F` names the padded extent as a mapping rather than a constant. A literal extent writes it as
/// [`Broadcast`], and an extent the caller derives from an axis writes it as [`Symbol`], which
/// keeps such an extent in type space: reading a size off a generic parameter in const-argument
/// position is what `generic_const_exprs` is for, and reading it in a const initializer is not.
///
/// `KIND` selects the padding flavour at the type level. Defaults to
/// [`PaddingKind::Top`] (arbitrary values); use [`PaddingKind::Zero`] for
/// slots known to hold zero (e.g. produced by the Fetch Adapter's masking
/// stage), or [`PaddingKind::Bottom`] for inaccessible regions.
#[primitive(mapping::Padding)]
#[derive(Debug, Clone)]
pub struct Padding<L, F, const KIND: PaddingKind = { PaddingKind::Top }> {
    _marker: PhantomData<(L, F)>,
}
// ANCHOR: padding_impl
impl<L, F, const KIND: PaddingKind> M for Padding<L, F, KIND>
where
    L: M,
    F: Count,
{
    const SIZE: usize = F::SIZE;

    fn to_value() -> Mapping {
        Mapping::Padding {
            inner: RBox::new(L::to_value()),
            padding: F::SIZE,
            kind: KIND,
        }
    }

    fn map(i: usize) -> Cell {
        if i >= F::SIZE {
            Cell::OutOfBounds
        } else if i >= L::SIZE {
            Cell::Padding(KIND)
        } else {
            L::map(i)
        }
    }
}
// ANCHOR_END: padding_impl

/// Pair expression of two expressions.
#[primitive(mapping::Pair)]
#[derive(Debug, Clone)]
pub struct Pair<L, R> {
    _marker: PhantomData<(L, R)>,
}
// ANCHOR: pair_impl
impl<L, R> M for Pair<L, R>
where
    L: M,
    R: M,
{
    const SIZE: usize = L::SIZE * R::SIZE;

    fn to_value() -> Mapping {
        Mapping::Pair {
            left: RBox::new(L::to_value()),
            right: RBox::new(R::to_value()),
        }
    }

    fn map(i: usize) -> Cell {
        if i >= Self::SIZE {
            return Cell::OutOfBounds;
        }
        let l = L::map(i / R::SIZE);
        let r = R::map(i % R::SIZE);
        match l {
            Cell::OutOfBounds => Cell::OutOfBounds,
            Cell::Padding(kind) => Cell::Padding(kind),
            Cell::Index(mut left) => match r {
                Cell::Index(right) => {
                    left.add(right);
                    Cell::Index(left)
                }
                Cell::Padding(kind) => Cell::Padding(kind),
                Cell::OutOfBounds => Cell::OutOfBounds,
            },
        }
    }
}
// ANCHOR_END: pair_impl
