//! Lowering fixtures for each lift-dimension subset and adapter chain.

use furiosa_opt_std::prelude::*;

axes![R = 4, S = 2, T = 2, P256 = 256, P128 = 128, U32 = 32, U8 = 8, K = 16];

macro_rules! mix_kernels {
    ($($kernel:ident: [$($dimension:ident),+], $chain:ident;)*) => {
        $(mix_kernels!(@subset [$($dimension),+], $chain, $kernel);)*

        /// Kernels generated by the lift-dimension and adapter matrix.
        pub const KERNELS: &[&str] = &[$(stringify!($kernel)),*];
    };

    (@subset [chip], $chain:ident, $kernel:ident) => { mix_kernels!(@chain $chain, $kernel,
        4, [R], [1 # 2], [1 # 2], [], [P256], [P256], [P256], [R],
        { fetch_chip_lift m![R], m![1]; }); };
    (@subset [cluster], $chain:ident, $kernel:ident) => { mix_kernels!(@chain $chain, $kernel,
        1, [1], [2], [S], [S,], [P256], [P256], [P256], [S],
        { fetch_cluster_lift m![S], m![1]; }); };
    (@subset [slice], $chain:ident, $kernel:ident) => { mix_kernels!(@chain $chain, $kernel,
        1, [1], [1 # 2], [1 # 2], [], [P128], [P128, 2], [P128, T], [T],
        { fetch_slice_lift m![P128, T], m![1]; }); };
    (@subset [chip, cluster], $chain:ident, $kernel:ident) => { mix_kernels!(@chain $chain, $kernel,
        4, [R], [2], [S], [S,], [P256], [P256], [P256], [R, S],
        { fetch_chip_lift m![R], m![S]; fetch_cluster_lift m![S], m![1]; }); };
    (@subset [chip, slice], $chain:ident, $kernel:ident) => { mix_kernels!(@chain $chain, $kernel,
        4, [R], [1 # 2], [1 # 2], [], [P128], [P128, 2], [P128, T], [R, T],
        { fetch_chip_lift m![R], m![T]; fetch_slice_lift m![P128, T], m![1]; }); };
    (@subset [cluster, slice], $chain:ident, $kernel:ident) => { mix_kernels!(@chain $chain, $kernel,
        1, [1], [2], [S], [S,], [P128], [P128, 2], [P128, T], [S, T],
        { fetch_cluster_lift m![S], m![T]; fetch_slice_lift m![P128, T], m![1]; }); };
    (@subset [chip, cluster, slice], $chain:ident, $kernel:ident) => { mix_kernels!(@chain $chain, $kernel,
        4, [R], [2], [S], [S,], [P128], [P128, 2], [P128, T], [R, S, T],
        { fetch_chip_lift m![R], m![S, T]; fetch_cluster_lift m![S], m![T];
          fetch_slice_lift m![P128, T], m![1]; }); };

    (@subset [$($dimension:ident),+], $chain:ident, $kernel:ident) => {
        compile_error!("lift dimensions must be ordered chip, cluster, slice");
    };

    (@chain plain, $($subset:tt)*) => {
        mix_kernels!(@build i8, i8, U32, {}, m![1], m![U32], m![U32], $($subset)*);
    };
    (@chain cast, $($subset:tt)*) => {
        mix_kernels!(@build i8, i32, U8, { .fetch_cast::<i32>() }, m![1], m![U8], m![U8],
            $($subset)*);
    };
    (@chain lookup, $($subset:tt)*) => {
        mix_kernels!(@build f4e2m1, f32, K,
            { .fetch_table_lookup::<f8e4m3>().fetch_cast::<f32>() },
            m![K / 8], m![K % 8], m![K / 8, K % 8], $($subset)*);
    };

    (@build $d:ty, $out_d:ty, $packet:ident, { $($adapter:tt)* }, $collect:ty, $trim:ty,
     $element:ty, $kernel:ident, $chips:literal, [$($chip2:tt)*], [$($cluster:tt)*],
     [$($cluster2:tt)*], [$($cluster_dimension:tt)*], [$($live:tt)*], [$($slice:tt)*],
     [$($slice2:tt)*], [$($broadcast:ident),+], { $($lift:ident $lifted:ty, $rest:ty;)+ }) => {
        #[device(chip = $chips)]
        pub fn $kernel(
            device: &mut Device,
            input: &HbmTensor<$d, m![$chips], m![$($live)*, $($broadcast),+, $packet]>,
        ) -> HbmTensor<$out_d, m![$($chip2)*], m![$($cluster_dimension)* $($slice2)*, $packet]> {
            let dm: DmTensor<$d, m![$chips], m![$($cluster)*], m![$($slice)*],
                m![$($broadcast),+, $packet]> =
                input.to_dm::<m![$($cluster)*], m![$($slice)*], m![$($broadcast),+, $packet]>(
                    &mut device.tdma,
                );

            let result: DmTensor<$out_d, m![$($chip2)*], m![$($cluster2)*], m![$($slice2)*],
                $element> = device
                .main
                .begin(dm.view())
                .fetch::<m![$($broadcast),+], m![$packet]>()
                $(.$lift::<$lifted, $rest>())+
                $($adapter)*
                .collect::<$collect, $trim>()
                .commit_trim::<$trim>()
                .commit();

            result.to_hbm::<m![$($cluster_dimension)* $($slice2)*, $packet]>(&mut device.tdma)
        }
    };
}

mix_kernels! {
    mix_chip_plain: [chip], plain;
    mix_chip_cast: [chip], cast;
    mix_chip_lookup: [chip], lookup;
    mix_cluster_plain: [cluster], plain;
    mix_cluster_cast: [cluster], cast;
    mix_cluster_lookup: [cluster], lookup;
    mix_slice_plain: [slice], plain;
    mix_slice_cast: [slice], cast;
    mix_slice_lookup: [slice], lookup;
    mix_chip_cluster_plain: [chip, cluster], plain;
    mix_chip_cluster_cast: [chip, cluster], cast;
    mix_chip_cluster_lookup: [chip, cluster], lookup;
    mix_chip_slice_plain: [chip, slice], plain;
    mix_chip_slice_cast: [chip, slice], cast;
    mix_chip_slice_lookup: [chip, slice], lookup;
    mix_cluster_slice_plain: [cluster, slice], plain;
    mix_cluster_slice_cast: [cluster, slice], cast;
    mix_cluster_slice_lookup: [cluster, slice], lookup;
    mix_every_plain: [chip, cluster, slice], plain;
    mix_every_cast: [chip, cluster, slice], cast;
    mix_every_lookup: [chip, cluster, slice], lookup;
}
